### PR TITLE
Update publications.mdx - added links to microgrants

### PR DESCRIPTION
**Pull request by QuantumAli**
When creating a branch, it showed that this branch was already created? so I removed it and renamed, but still showed that this branch was made by _Nathan_, so I just proceeded as normal.

### CODE REVIEW

**Review by WrathfulSpatula — APPROVED** [review]

**Review by nathanshammah — CHANGES_REQUESTED** [review]
Thanks @QuantumAli, nice work. 

1. It is partially completed as we need to add the links also for the other sections (Other UF staff research and Unitary Labs research). 

2. If you really want to do an amazing job, we could take the opportunity to make the references more informative, using standards for citations of papers. For example: 

instead of 
```
[K-GRAPE: A Krylov Subspace approach for the efficient control of quantum many-body dynamics](https://arxiv.org/abs/2010.03598)
```
use the more comprehensive bibliographic style
```
Martin Larocca, Diego Wisniacki, *K-GRAPE: A Krylov Subspace approach for the efficient control of quantum many-body dynamics*, Phys. Rev. A *103*, 023107 (2021), [[2010.03598](https://arxiv.org/abs/2010.03598)], [doi:10.1103/PhysRevA.103.023107](https://doi.org/10.1103/PhysRevA.103.023107)
```
 
However, the second ask is a big request, so I am going to open a new issue for it, and in this PR you can tackle the first part only (URL only). Also, the second request should not be a blocker for site launch.

**Comment by QuantumAli** [comment]
Understood. 
1) The other links should be the ones that srila worked on
2) That is something that I will work on, goal to be completed before Thursday (Better practice with citation anyways)

**Comment by WrathfulSpatula** [comment]
@QuantumAli As Nathan is away, I can review his change request. Please try to keep the Thursday deadline you set, and have this in today if possible.

**Comment by QuantumAli** [comment]
Updated microgrants utilizing this link: https://cdn.journals.aps.org/files/styleguide-pr.pdf, if there are any issues, an example would provide quite useful.

**Review by WrathfulSpatula — APPROVED** [review]
This looks beautiful. Thank you for your careful attention to detail and hard work!

**Pull request merged**
