### PR TITLE
Update event images

### PR DESCRIPTION
**Pull request by srilakshmip03**

### CODE REVIEW

**Comment by nathanshammah** [comment]
Thanks @srilakshmip03, something maybe is off in the way you attach the images / they are rendered? See here: https://unitary-fund-git-update-event-images-the-glasshouse-project.vercel.app/community/events/

**Review by nathanshammah — CHANGES_REQUESTED** [review]
See comment above, @srilakshmip03 (and @joshdavenport, in case you can help). By the way, is there a gallery with the current images and related alphanumeric codes that we can look at?

**Comment by nathanshammah** [comment]
@srilakshmip03 what format did you use.

**Comment by srilakshmip03** [comment]
@nathanshammah I uploaded each image to https://unitary-fund.vercel.app/author/image, then I just copied each generated code and pasted it into markdown as plain text. I followed the same format from the two examples - did I miss a step?

**Comment by nathanshammah** [comment]
It actually sounds correct to me. What format were they? png?

**Comment by srilakshmip03** [comment]
Yep, all PNG

**Comment by nathanshammah** [comment]
let me try to push one change

**Comment by nathanshammah** [comment]
Thanks @joshdavenport, your commit has fixed most images, https://unitary-fund-p3jdgnyc6-the-glasshouse-project.vercel.app/community/events/
I wonder what is broken with the remaining ones, as it seems to import the image frame. Cc to @srilakshmip03. What url shall we use for cloudinary?

**Comment by joshdavenport** [comment]
@nathanshammah Yes indeed, and I believe I know why the others aren't loading but just working through it atm. Leave it with me for now. Will get back in touch

**Comment by joshdavenport** [comment]
Remaining images restored, should be all good now @nathanshammah 👍

**Comment by nathanshammah** [comment]
Thanks @joshdavenport!

**Review by nathanshammah — APPROVED** [review]

**Pull request merged**
