### PR TITLE
Fix image rendering issues in blog posts

### PR DESCRIPTION
**Pull request by srilakshmip03**
I used the image with the same name as the blog post itself - not sure if these are supposed to be the same one

### CODE REVIEW

**Review by WrathfulSpatula — APPROVED** [review]

**Comment by srilakshmip03** [comment]
[New link](https://unitary-fund-git-fix-images-the-glasshouse-project.vercel.app/posts/metriq_quantum_volume)

**Review by nathanshammah — CHANGES_REQUESTED** [review]
Thanks @srilakshmip03, overall they look great. It would be great to resize a bit the images that are too big, e.g., in the blog post for the [new Mitiq paper](https://unitary-fund-git-fix-images-the-glasshouse-project.vercel.app/posts/new_version_mitiq_paper) and in the one announcing uHACK 2023, the images are too large. I am not sure how to do it, as in the test blog post the sizes were not set ([link](https://raw.githubusercontent.com/tghp/unitary-fund/81a09b5661ba774f7ee48255499f667fec8b7b6a/src/content/blog/test-post.md)). In other frameworks I used an html line in markdown, not sure this will work here. Checking also with @WrathfulSpatula.

**Comment by WrathfulSpatula** [comment]
I'm not familiar with the API of our image-hosting service, but there's often a parameter to control resizing of an image when it's served. Alternatively, this [StackOverflow Q&A](https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown) suggests using just a raw HTML `` tag.

**Comment by srilakshmip03** [comment]
[new_version_mitiq_paper.md](https://unitary-fund-kvycwma93-the-glasshouse-project.vercel.app/posts/new_version_mitiq_paper)
[unitaryHACK2021.md](https://unitary-fund-5slqia19g-the-glasshouse-project.vercel.app/posts/unitaryhack2021)
[2023_unitaryHACK.md](https://unitary-fund-1oks9e4bn-the-glasshouse-project.vercel.app/posts/2023_unitaryhack)
[metriq_quantum_volume.md](https://unitary-fund-nz7jc3wle-the-glasshouse-project.vercel.app/posts/metriq_quantum_volume)

**Review by WrathfulSpatula — APPROVED** [review]
LGTM!

**Pull request merged**
